# Offset is the offset of the tooltip from the mouse cursor on the screen
offset.X = 5
offset.Y = 20

# Padding is for padding that you add on the stylesheet
# As the size of the tooltip is dynamically determined..
# ..the padding will be added to its final size
padding.width = 10
padding.height = 10

# Pos of text
lblText.X = 5
lblText.Y = 5

# Width is used to determine where each line "ends" for word wrapping
lblText.width = 300
# Used for bounding rectangle of text. Keep height extremely large
lblText.height = 2000
