width = 1000
height = 600

channelAdmins.X = 0
channelAdmins.Y = 10
channelAdmins.width = ~formwidth - 51
channelAdmins.height = ~formheight - 106
channelAdmins.Z = 5

cmdSave.X = 252
cmdSave.Y = 10
cmdSave.width = 120
cmdSave.height = 28
cmdSave.Z = 20


# TabWidgets
tabOptions.X = 50
tabOptions.Y = 50
tabOptions.width = ~formwidth - 50
tabOptions.height = ~formheight - 68
tabOptions.Z = 5

tabAnnOptions.X = 0
tabAnnOptions.Y = 10
tabAnnOptions.width = ~formwidth - 25
tabAnnOptions.height = ~formheight - 28
tabAnnOptions.Z = 5

# TextEdits
txtEdit.X = 0
txtEdit.Y = 5
txtEdit.width = $channelAdmins.width - 3
txtEdit.height = ~formheight - 145
txtEdit.Z = 3

txtPreview.X = 0
txtPreview.Y = 5
txtPreview.width = $channelAdmins.width - 3
txtPreview.height = ~formheight - 145
txtPreview.Z = 3

# BordersTop 

darkborder.X = 25
darkborder.Y = 82
darkborder.width = ~formwidth - 25
darkborder.height = 2

BorderleftTop.X = 25
BorderleftTop.Y = 25
BorderleftTop.width = ~formwidth - 25
BorderleftTop.height = ~formheight - 45

iconedit.X = 60
iconedit.Y = 93
iconedit.Z = 1
iconedit.width = 16
iconedit.height = 16

iconpreview.X = 185
iconpreview.Y = 95
iconpreview.width = 16
iconpreview.height = 16

designbullets.X = ~formwidth - $designbullets.width
designbullets.Y = 35 
designbullets.Z = 4
designbullets.width = 355
designbullets.height = 78


