var d = 12
var h = 20
var s = $gSigned.Y - $gGames.Y - $gGames.height - $h - $td - 5
var td = 10

#====== STARTED GAMES ======
startGamesHeader.X = 3
startGamesHeader.Y = 17
startGamesHeader.height = 54
startGamesHeader.width = 207
startGamesHeader.Z = 1

startGamesBody.X = 5
startGamesBody.Y = $startGamesHeader.Y + $startGamesHeader.height -15
startGamesBody.height = (~formheight - $Signbg.height - 222) / 2
startGamesBody.width = 199
startGamesBody.Z = 1

gGames.X = 28
gGames.Y = 25
gGames.height = 20
gGames.width = ~formwidth - 14
gGames.Z = 2

lcdGames.X = ~formwidth - 60
lcdGames.Y = 19
lcdGames.width = 47
lcdGames.height = 32
lcdGames.Z = 7

lstGames.X = 11
lstGames.Y = $startGamesBody.Y
lstGames.width = 187
lstGames.height = $startGamesBody.height + 65
lstGames.Z = 10

#==========================


#====== OPEN GAMES ======
openGamesHeader.X = 3
openGamesHeader.Y = $lstGames.Y + $lstGames.height
openGamesHeader.height = 40
openGamesHeader.width = 207
openGamesHeader.Z = 2

openGamesBody.X = 5
openGamesBody.Y = $openGamesHeader.Y + $openGamesHeader.height
openGamesBody.height = (~formheight - $Signbg.height - 140) / 2
openGamesBody.width = 199
openGamesBody.Z = 2


gOpen.X = 28
gOpen.Y = $lstGames.Y + $lstGames.height + 13
gOpen.height = 20
gOpen.width = ~formwidth - $d
gOpen.Z = 3

lstOpenGames.X = 11
lstOpenGames.Y = $openGamesHeader.Y + $openGamesHeader.height + 1
lstOpenGames.width = 187
lstOpenGames.height = $openGamesBody.height + 18
lstOpenGames.Z = 3

#========================


#====== SIGNED ======
gSigned.X = 28
gSigned.Y = $lstSigned.Y - ~height - 8
gSigned.height = 20
gSigned.width = ~formwidth - 12
gSigned.Z = 10

Signbg.X = 3
Signbg.Y = ~formheight - ~height
Signbg.height = 271
Signbg.width = 205
Signbg.Z = 2

lstSigned.X = 11
lstSigned.Y = $Signbg.Y + 42
lstSigned.height = 164
lstSigned.width = 187
lstSigned.Z = 2

#====================


#====== SIGN ======
cmdSign.X = 6
cmdSign.Y = $Signbg.Y + $Signbg.height - 58
cmdSign.width = 127
cmdSign.height = 40
cmdSign.Z = 15

Modes.X = $cmdSign.X + $cmdSign.width + 5
Modes.Y = $cmdSign.Y
Modes.width = 64
Modes.height = 40
Modes.Z = 15
#==================
