# BUG :: height or width have no effect here, need to figure out why that is the case
width = 330
height = 500
fixed-size = 1


allChannels.X = 20
allChannels.Y = 50
allChannels.width = ~formwidth - 22
allChannels.height = ~formheight - 50
