COLOR_ERROR = #cf4444
COLOR_UI_HIGHLIGHT = #3fd968
COLOR_CHAT_HIGHLIGHT = #d1650a
COLOR_CHAT_JOINED = #75756f
COLOR_CHAT_LEFT = #75756f
COLOR_CHAT_GAMES = #3fd968
COLOR_FRIENDSLIST = #c9218e
COLOR_HELP = #1273c4
COLOR_CHAT_MESSAGE = #1e1e1c
COLOR_CHAT_USER = #1273c4
COLOR_CHAT_CLAN_TAG = #75756f

COLOR_STATUS_ONLINE = #1e9e4e
COLOR_STATUS_BUSY = #cf4444
COLOR_STATUS_INGAME = #1273c4
COLOR_STATUS_INVISIBLE = #75756f
COLOR_STATUS_AWAY = #bd8404

CSS_STYLE_HREF = text-decoration: none;


# web-links, etc...
DEFAULT_PROTOCOL_COLOR = #1273c4


#DEFINED COLOR BLOCK XX
X0 = #1e1e1c
X1 = #3fd968
