
Games.X = ~formwidth  - $Games.width - 2
Games.Y = 20
Games.width = 210
Games.height = ~formheight - 20
Games.Z = 3


var cw = ~formwidth - $Games.width - 5
var ch = ~formheight

var d = 5
var y = 10
var chatHeight = $ch - $txtChatInput.height - $d - $y

# - 4 :: because 10 - 6 = 4, and 6 is the distance between txtChat and lstUsers
lstUsers.X = $cw - ~width + 3
lstUsers.Y = $txtChat.Y
lstUsers.width = 240
lstUsers.height = $txtChat.height
lstUsers.Z = 2

txtChatInput.height = 42
txtChatInput.width = $cw
txtChatInput.X = $txtChat.X
txtChatInput.Y = $ch - ~height - $d - 12
txtChatInput.Z = 25

cmdEmoji.height = 22
cmdEmoji.width = 22
cmdEmoji.X = $txtChatInput.X + 15
cmdEmoji.Y = $txtChatInput.Y + 10
cmdEmoji.Z = 26



bggames.X = $lstUsers.X + $lstUsers.width + 3
bggames.Y = $lstUsers.Y - 54
bggames.width = 300
bggames.height = $txtChat.height + 125
bggames.Z = 2

bullets.X = $lstUsers.X - 70
bullets.Y = 20
bullets.width = 289
bullets.height = 50
bullets.Z = 2



txtChat.X = 0
txtChat.Y = $d + 69
txtChat.width = $cw - $lstUsers.width - 1
txtChat.height = $chatHeight - 83
txtChat.Z = 3

Name.X = $txtChat.X = 0
Name.Y = $txtChat.Y  - $Name.height - 10
Name.width = 204
Name.height = 32
Name.Z = 3

