var d = 5
var y = 10
var chatHeight = ~formheight - $txtChatInput.height - $d - $y

# IF AN OBJECT DOES NOT HAVE A PROPERTY IN CONFIG.INI
# AND THEN REPLACEDYNAMICWIDGET IS USED ON THIS OBJECT
# THE CLIENT WILL CRASH WITH A 'UI LOAD ERROR'
lstUsers.width = 0
lstUsers.height = 0

txtChatInput.height = 42
txtChatInput.width = ~formwidth - 15
txtChatInput.X = $txtChat.X
txtChatInput.Y = $txtChat.Y + $txtChat.height + 7
txtChatInput.Z = 25

cmdEmoji.height = 22
cmdEmoji.width = 22
cmdEmoji.X = $txtChatInput.X + 15
cmdEmoji.Y = $txtChatInput.Y + 10
cmdEmoji.Z = 26

txtChat.X = 0
txtChat.Y = $d + 69
txtChat.width = ~formwidth - 15
txtChat.height = $chatHeight  - 83
txtChat.Z = 6

lblname.X = $txtChat.X = 0
lblname.Y = $txtChat.Y  - $lblname.height - 10
lblname.width = 204
lblname.height = 32
lblname.Z = 9

bullets.X = ~formwidth - 300
bullets.Y = 20
bullets.width = 289
bullets.height = 50
bullets.Z = 2