width = 727
height = 620
fixed-size = 1


var ds = 12





avatar.X = 104
avatar.Y = 119
avatar.width = 124
avatar.height = 124
avatar.Z = 1

rankedicon.X = 14
rankedicon.Y = 23
rankedicon.width = 300
rankedicon.height = 275
rankedicon.Z = 50

avatarmask.X = 103
avatarmask.Y = 118
avatarmask.width = 126
avatarmask.height = 126
avatarmask.Z = 3


txtRgid.X = 180
txtRgid.Y = $lblGames.Y
txtRgid.width = $lblGames.width
txtRgid.height = $lblGames.height
txtRgid.Z = 100

lblExpressionsDesc.X = $lblDescription_desc.X
lblExpressionsDesc.Y = 263
lblExpressionsDesc.width = 348
lblExpressionsDesc.height = 20
lblExpressionsDesc.Z = 3

# Flags are 16x11 in dimension
lblFlag.X = 190
lblFlag.Y = $avatar.Y + $avatar.height - 25
lblFlag.width = 26
lblFlag.height = 26
lblFlag.Z = 999

lblAccount.X = 33
lblAccount.Y = $avatar.Y + $avatar.width + 27
lblAccount.width = 200
lblAccount.height = 0
lblAccount.Z = 1

lblDescription.X = 342
lblDescription.Y = 49
lblDescription.width = 362
lblDescription.height = 240
lblDescription.Z = 5

lblDescription_desc.X = 387
lblDescription_desc.Y = 20
lblDescription_desc.width = 250
lblDescription_desc.height = 20
lblDescription_desc.Z = 1

lblGames.X = 71
lblGames.Y = 255
lblGames.width = 85
lblGames.height = 26
lblGames.Z = 1

lblLastLogin.X = 82
lblLastLogin.Y = $lblRegistered.Y + 35
lblLastLogin.width = 220
lblLastLogin.height = 25
lblLastLogin.Z = 1

lblName.X = 30
lblName.Y = 10
lblName.width = 270
lblName.height = 21
lblName.Z = 1

lblAge.X = 82
lblAge.Y = 354
lblAge.width = 220
lblAge.height = 20
lblAge.Z = 1

lblNationality.X = 82
lblNationality.Y = $lblResidence.Y  + 35
lblNationality.width = 220
lblNationality.height = 20
lblNationality.Z = 1

lblRegistered.X = 82
lblRegistered.Y = $lblNationality.Y + 35
lblRegistered.width = 220
lblRegistered.height = 20
lblRegistered.Z = 1

lblResidence.X = 82
lblResidence.Y = $lblSex.Y + 38
lblResidence.width = 220
lblResidence.height = 20
lblResidence.Z = 1

lblSex.X = 82
lblSex.Y = $lblAge.Y + 35
lblSex.width = 220
lblSex.height = 20
lblSex.Z = 1

lblTitle.X = $lblName.X
lblTitle.Y = $lblName.Y + $lblName.height + 3
lblTitle.width = 270
lblTitle.height = 25
lblTitle.Z = 1

lblTitle2.X = $lblName.X
lblTitle2.Y = $lblTitle.Y + $lblTitle.height + 3
lblTitle2.width = 270
lblTitle2.height = 20
lblTitle2.Z = 1

progressBar.X = $avatar.X + ($avatar.width - ~width) / 2
progressBar.Y = $avatar.Y + ($avatar.height - ~height) / 2
progressBar.width = 70
progressBar.height = 14
progressBar.Z = 2

tableAccess.Z = 2
tableAccess.X = 347
tableAccess.Y = 341
tableAccess.width = 356
tableAccess.height = 238
tableAccess.Z = 2

