width = 710
height = 435
fixed-size = 1
var x = 310

cmdSave.X = ~formwidth - ~width - 89
cmdSave.Y = ~formheight - $cmdSave.height - 66
cmdSave.height = 38
cmdSave.width = 137
cmdSave.Z = 4

chaticon.X = 45
chaticon.Y = 15
chaticon.width = 20
chaticon.height = 19

friendsicon.X = 170
friendsicon.Y = 15
friendsicon.width = 21
friendsicon.height = 20

soundsicon.X = 308
soundsicon.Y = 14
soundsicon.width = 21
soundsicon.height = 20


othericon.X = 448
othericon.Y = 15
othericon.width = 18
othericon.height = 17


dotaicon.X = 586
dotaicon.Y = 13
dotaicon.width = 21
dotaicon.height = 22

tabWidget.X = 10
tabWidget.Y = 11
tabWidget.width = ~formwidth - 20
tabWidget.height = ~formheight - 40

#===== Chat =====

gTimestamps.X = 10
gTimestamps.Y = 30
gTimestamps.width = 320
gTimestamps.height = 20

lblTimestamp.X = 20
lblTimestamp.Y = 55
lblTimestamp.width = 320
lblTimestamp.height = 16

txtTimestamp.X = 40
txtTimestamp.Y = 81
txtTimestamp.width = 260
txtTimestamp.height = 26

lblSettings.X = 20
lblSettings.Y = 130
lblSettings.width = 291
lblSettings.height = 20

cTimestampChannels.X = 20
cTimestampChannels.Y = 155
cTimestampChannels.width = 301
cTimestampChannels.height = $eH

cTimestampGames.X = 20
cTimestampGames.Y = 155 + $eHs * 1
cTimestampGames.width = 301
cTimestampGames.height = $eH

cTimestampMessages.X = 20
cTimestampMessages.Y = 155 + $eHs * 2
cTimestampMessages.width = 301
cTimestampMessages.height = $eH

lblMaxLines.X = 20
lblMaxLines.Y = 270
lblMaxLines.width = 291
lblMaxLines.height = 20

txtMaxLines.X = $lblMaxLines.X + 20
txtMaxLines.Y = $lblMaxLines.Y + 30
txtMaxLines.width = 260
txtMaxLines.height = 26


gCustomChannels.X = 380
gCustomChannels.Y = 30
gCustomChannels.width = 281
gCustomChannels.height = 251

txtCustomRoomJoinlist.X = 390
txtCustomRoomJoinlist.Y = 55
txtCustomRoomJoinlist.width = 220
txtCustomRoomJoinlist.height = 200

lblExpressions.X = $x
lblExpressions.Y = 10000
lblExpressions.width = 291
lblExpressions.height = 16

lblExpressionsDesc.X = $x
lblExpressionsDesc.Y = 11000
lblExpressionsDesc.width = 291
lblExpressionsDesc.height = 51



#================

#===== Friends =====
var eH = 32
var eHs = 26
var eW = 500

cBuddyStateOnline.X = 20
cBuddyStateOnline.Y = 55
cBuddyStateOnline.width = $eW
cBuddyStateOnline.height = $eH

cBuddyStateOffline.X = 20
cBuddyStateOffline.Y = 55 + $eHs
cBuddyStateOffline.width = $eW
cBuddyStateOffline.height = $eH

cBuddyStateAway.X = 20
cBuddyStateAway.Y = 55 + $eHs * 2
cBuddyStateAway.width = $eW
cBuddyStateAway.height = $eH

cBuddyStateIngame.X = 20
cBuddyStateIngame.Y = 55 + $eHs * 3
cBuddyStateIngame.width = $eW
cBuddyStateIngame.height = $eH

cIgnoreHighlight.X = 20
cIgnoreHighlight.Y = 115 + $eHs * 4
cIgnoreHighlight.width = $eW
cIgnoreHighlight.height = $eH

cIgnorePrivate.X = 20
cIgnorePrivate.Y = 115 + $eHs * 5
cIgnorePrivate.width = $eW
cIgnorePrivate.height = $eH

cIgnoreChat.X = 20
cIgnoreChat.Y = 115 + $eHs * 6
cIgnoreChat.width = $eW
cIgnoreChat.height = $eH

gFriendslist.X = 10
gFriendslist.Y = 30
gFriendslist.width = 311
gFriendslist.height = $eH

gIgnoreList.X = 10
gIgnoreList.Y = 195
gIgnoreList.width = 311
gIgnoreList.height = $eH
#===================

#===== Sounds =====
gHighlight.X = 370
gHighlight.Y = 30
gHighlight.width = 311
gHighlight.height = 251

gSounds.X = 10
gSounds.Y = 30
gSounds.width = 281
gSounds.height = 81

cSoundGameHosted.X = 20
cSoundGameHosted.Y = 55
cSoundGameHosted.width = 321
cSoundGameHosted.height = $eH

cSoundGameStarts.X = 20
cSoundGameStarts.Y = 55 + $eHs * 1
cSoundGameStarts.width = 321
cSoundGameStarts.height = $eH

cSoundLogin.X = 20
cSoundLogin.Y = 55 + $eHs * 2
cSoundLogin.width = 321
cSoundLogin.height = $eH

cSoundShutdown.X = 20
cSoundShutdown.Y =  55 + $eHs * 3
cSoundShutdown.width = 321
cSoundShutdown.height = $eH

lblHighlight.X = 380
lblHighlight.Y = 55
lblHighlight.width = 300
lblHighlight.height = 40

lblHighlight_Online.X = $x + 90
lblHighlight_Online.Y = 130
lblHighlight_Online.width = 111
lblHighlight_Online.height = 20

lblHighlight_Away.X = $x + 90
lblHighlight_Away.Y = 165
lblHighlight_Away.width = 111
lblHighlight_Away.height = 20

lblHighlight_Ingame.X = $x + 90
lblHighlight_Ingame.Y = 200
lblHighlight_Ingame.width = 111
lblHighlight_Ingame.height = 20

cHighlight_Online.X = 480
cHighlight_Online.Y = 130
cHighlight_Online.width = 130
cHighlight_Online.height = 25

cHighlight_Away.X = 480
cHighlight_Away.Y = 165
cHighlight_Away.width = 130
cHighlight_Away.height = 25

cHighlight_Ingame.X = 480
cHighlight_Ingame.Y = 200
cHighlight_Ingame.width = 130
cHighlight_Ingame.height = 25



gAliases.X = 10
gAliases.Y = 190
gAliases.width = 261
gAliases.height = 116

txtAliases.X = 19
txtAliases.Y = 218
txtAliases.width = 241
txtAliases.height = 91
#==================

#===== Other =====
lblMainWindowButtons.X = 20
lblMainWindowButtons.Y = 25
lblMainWindowButtons.width = 601
lblMainWindowButtons.height = 30

cClientExit.X = 20
cClientExit.Y = 52
cClientExit.width = 601
cClientExit.height = $eH

cClientMinimize.X = 20
cClientMinimize.Y = 56 + $eHs
cClientMinimize.width = 601
cClientMinimize.height = $eH

lblMapDownloader.X = 20
lblMapDownloader.Y = 90 + $eHs
lblMapDownloader.width = 601
lblMapDownloader.height = $eHs

cMapPopup.X = 20
cMapPopup.Y = 120 + $eHs
cMapPopup.width = 601
cMapPopup.height = $eHs

lblClientLog.X = 20
lblClientLog.Y = 180
lblClientLog.width = 591
lblClientLog.height = 20

cClientLog.X = 20
cClientLog.Y = 200
cClientLog.width = 581
cClientLog.height = $eH



lblCustomization.X = 20
lblCustomization.Y = 240
lblCustomization.width = 591
lblCustomization.height = 30

cLanguages.X = 20
cLanguages.Y = 270
cLanguages.width = 250
cLanguages.height = 25

cSkins.X = 20
cSkins.Y = 305
cSkins.width = 250
cSkins.height = 25

lblLanguage.X = 285
lblLanguage.Y = 270
lblLanguage.width = 121
lblLanguage.height = 22

lblSkin.X = 285
lblSkin.Y = 305
lblSkin.height = 22
lblSkin.width = 50

#=================


#===== DotA =====

cmdFindWC3.X = 40
cmdFindWC3.Y = $txtWC3.Y + $lblLaunchOptions.height + 5
cmdFindWC3.width = 96
cmdFindWC3.height = 30

lblLaunchOptions.X = 25
lblLaunchOptions.Y = $txtWC3.Y + $lblLaunchOptions.height + 55
lblLaunchOptions.width = 601
lblLaunchOptions.height = 20

lblStartGameDoNotAskAgain.X = 25
lblStartGameDoNotAskAgain.Y = $txtLaunchOptions.Y + $lblLaunchOptions.height + 20
lblStartGameDoNotAskAgain.width = 190
lblStartGameDoNotAskAgain.height = 20

cStartGameDoNotAskAgain.X = $lblStartGameDoNotAskAgain.X + $lblStartGameDoNotAskAgain.width + 10
cStartGameDoNotAskAgain.Y = $lblStartGameDoNotAskAgain.Y - 7
cStartGameDoNotAskAgain.width = 38
cStartGameDoNotAskAgain.height = 30


lblWC3.X = 25
lblWC3.Y = 45
lblWC3.width = 601
lblWC3.height = 20

txtLaunchOptions.X = 40
txtLaunchOptions.Y = $lblLaunchOptions.Y + $txtLaunchOptions.height + 5
txtLaunchOptions.width = 411
txtLaunchOptions.height = 20

txtWC3.X = 40
txtWC3.Y = $lblWC3.Y + $lblWC3.height  + 5
txtWC3.width = 411
txtWC3.height = 20

#================
