width = 500
height = 500

var d = 21

cmdAdd.X = ~formwidth - $cmdAdd.width - 40
cmdAdd.Y = 10
cmdAdd.width = 51
cmdAdd.height = 51
cmdAdd.Z = 200

tabtop1.height = 48
tabtop1.width = 177
tabtop1.X = 0
tabtop1.Y = 0
tabtop1.Z = 99

tabtop2.height = 48
tabtop2.width = ~formwidth - 207
tabtop2.X = $tabtop1.X + $tabtop1.width
tabtop2.Y = $tabtop1.Y
tabtop2.Z = 99

tabtop3.height = 48
tabtop3.width = 30
tabtop3.X = $tabtop2.X + $tabtop2.width
tabtop3.Y = $tabtop1.Y
tabtop3.Z = 99

tabbottom.height = 20
tabbottom.width = ~formwidth
tabbottom.X = 0
tabbottom.Y = ~formheight - 20
tabbottom.Z = 99

scrollBar.height = ~formheight - 70
scrollBar.width = 8
scrollBar.X = ~formwidth - ~width - 2
scrollBar.Y = 48
scrollBar.Z = 99

myFriends.X = 6
myFriends.Y = 40
#myFriends.Y = $d + 1 ---IS not modifiable. If you change it the client´s friendlist will not behave properly. DO NOT TOUCH THIS VALUE
myFriends.width = ~formwidth - $scrollBar.width -20
# myFriends.height IS not modifiable. If you change it the client´s friendlist will not behave properly. DO NOT TOUCH THIS VALUE
myFriends.height = ~formheight - 60