
#====== PROFILE WIDGET ======
Profile.X = 0
Profile.Y = 0
Profile.height = 210
Profile.width = 230
Profile.Z = 2

XP.X = 25
XP.Y = $DescriptionBG.Y + 10
XP.width = 180
XP.height = 15
XP.Z = 12

profileimg.X = 20
profileimg.Y = 53
profileimg.width = 205
profileimg.height = 74
profileimg.Z = 3 

RemainingXP.X = $XP.X
RemainingXP.Y = $XP.Y
RemainingXP.width = $XP.width
RemainingXP.height = $XP.height
RemainingXP.Z = 13

Description.X = 13
Description.Y = $XP.Y + $XP.height + 10
Description.width = $Profile.width - 26
Description.height = 42
Description.Z = 4

Descriptionlbl.X = 23
Descriptionlbl.Y = $XP.Y + $XP.height - 15
Descriptionlbl.width = $Profile.width - 45
Descriptionlbl.height = 25
Descriptionlbl.Z = 5

DescriptionBG.X = 13
DescriptionBG.Y = $Avatar.Y + $Avatar.height + 38
DescriptionBG.width = $Profile.width - 26
DescriptionBG.height = 77
DescriptionBG.Z = 3



Name.X = ($Profile.width - $Name.width) / 2
Name.Y = 112
Name.width = 148
Name.height = 20
Name.Z = 5

design2.X = 12
design2.Y = 45
design2.width = 205
design2.height = 2
design2.Z = 4

Status.X = 20
Status.Y = 20
Status.width = 190
Status.height = 20
Status.Z = 4

HideShadowH.X = $Status.X + $Status.width - 13
HideShadowH.Y = $Status.Y + 13
HideShadowH.width = 12
HideShadowH.height = 1
HideShadowH.Z = 4

HideShadowV.X = $Status.X + $Status.width - 2
HideShadowV.Y = $Status.Y + 7
HideShadowV.width = 1
HideShadowV.height = 6
HideShadowV.Z = 4

Avatar.X = 90
Avatar.Y = 55
Avatar.width = 50
Avatar.height = 50
Avatar.Z = 5

AvatarMask.X = $Avatar.X
AvatarMask.Y = $Avatar.Y
AvatarMask.width = 50
AvatarMask.height = 50
AvatarMask.Z = 7

StatusIcon.X = 10
StatusIcon.Y = 20
StatusIcon.width = 20
StatusIcon.height = 20
StatusIcon.Z = 8
